### ISSUE TITLE
`ct-fetch` sleeps most of the time

### ISSUE THREAD

**Issue by damz** [jcjones/ct-mapreduce#2]
Because `LogDownloader.EntryChan` is an unbuffered channel, and `LogDownloader.downloadCTRangeToChannel` has some weird backoff logic, a `ct-fetch` process ends up sleeping most of the time.

Making `LogDownloader.EntryChan` a buffered channel of the size of the batch increases the `ct-fetch` performance 10x in our environment:

```
diff --git a/cmd/ct-fetch/main.go b/cmd/ct-fetch/main.go
index 7bc12b1..f543574 100644
--- a/cmd/ct-fetch/main.go
+++ b/cmd/ct-fetch/main.go
@@ -71,7 +71,7 @@ type LogDownloader struct {
 func NewLogDownloader(db storage.CertDatabase) *LogDownloader {
        return &LogDownloader{
                Database:            db,
-               EntryChan:           make(chan CtLogEntry),
+               EntryChan:           make(chan CtLogEntry, 1024),
                Display:             utils.NewProgressDisplay(),
                ThreadWaitGroup:     new(sync.WaitGroup),
                DownloaderWaitGroup: new(sync.WaitGroup),
```

I'm not opening this as a PR, because I sense that the backoff logic should probably be removed too. The producer can, and probably just should, block on the channel when it is full.

**Comment by jcjones** [comment]
You're right, certainly. The backoff logic was helpful for `ct-sql` when the SQL database became slow (which happened as soon as you crammed 100M entries into it), and is nonsense here where our bottleneck is disk speed instead.

I'd be happy to take that PR though, if you want to open it!

**Comment by jcjones** [comment]
(I should also note: It's a simple enough change, I just can't really do it and test it until the weekend)

**Comment by jcjones** [comment]
(I should also note: It's a simple enough change, I just can't really do it and test it for a couple weekends,)
